version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - BACKEND_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/csm-backend
      - FRONTEND_REPO=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/csm-frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building Backend Docker image...
      - docker build -t $BACKEND_REPO:latest -t $BACKEND_REPO:$IMAGE_TAG ./backend
      - echo Building Frontend Docker image...
      - docker build --build-arg VITE_API_URL=/api/v1 -t $FRONTEND_REPO:latest -t $FRONTEND_REPO:$IMAGE_TAG ./frontend
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push $BACKEND_REPO:latest
      - docker push $BACKEND_REPO:$IMAGE_TAG
      - docker push $FRONTEND_REPO:latest
      - docker push $FRONTEND_REPO:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"csm-backend","imageUri":"%s"},{"name":"csm-frontend","imageUri":"%s"}]' $BACKEND_REPO:$IMAGE_TAG $FRONTEND_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
